/**
 * Mock data for the LifestyleJourneys section.
 * These are long-term, aspirational life-event journeys — discovery / inspiration,
 * not immediate shopping lists.
 */
export const LIFESTYLE_MOCK = [
  {
    id: "college_life",
    title: "Moving to College",
    tagline: "Everything for your first step away from home.",
    description: "From bedding and storage to gadgets and stationery — set up your hostel room and ace your semester.",
    productCount: 28,
    budget: { min: 8000, max: 25000 },
    query: "college hostel essentials bedding",
    icon: "graduation_cap",
    color: "#004B91",
    bg: "bg-blue-50",
  },
  {
    id: "fitness_lifestyle",
    title: "Starting a Fitness Journey",
    tagline: "Build healthy habits, one item at a time.",
    description: "Home gym gear, nutrition essentials, and wearables to kick-start your fitness transformation.",
    productCount: 22,
    budget: { min: 5000, max: 35000 },
    query: "fitness home gym yoga mat protein",
    icon: "dumbbell",
    color: "#C7511F",
    bg: "bg-orange-50",
  },
  {
    id: "study_lifestyle",
    title: "Building a Study Setup",
    tagline: "Create your perfect focus environment.",
    description: "Ergonomic desk, quality lighting, noise-cancelling headphones — a setup that helps you do your best work.",
    productCount: 15,
    budget: { min: 12000, max: 50000 },
    query: "study desk setup ergonomic monitor stand",
    icon: "monitor",
    color: "#131921",
    bg: "bg-gray-100",
  },
  {
    id: "first_home",
    title: "First Apartment Setup",
    tagline: "Turn a blank space into your home.",
    description: "Kitchen essentials, bedroom basics, and storage solutions — everything to make a new space feel like yours.",
    productCount: 45,
    budget: { min: 20000, max: 80000 },
    query: "apartment home essentials kitchen bedroom",
    icon: "home",
    color: "#067D62",
    bg: "bg-green-50",
  },
  {
    id: "wfh_lifestyle",
    title: "Work From Home Setup",
    tagline: "Upgrade your home office for peak productivity.",
    description: "Monitor arms, webcams, ergonomic chairs, and noise-cancelling headsets to stay focused all day.",
    productCount: 18,
    budget: { min: 15000, max: 60000 },
    query: "work from home office setup webcam monitor",
    icon: "briefcase",
    color: "#C7511F",
    bg: "bg-yellow-50",
  },
];
